# Generated by Django 5.2.4 on 2025-08-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("store", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for sellers",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sellers",
                to="store.category",
            ),
        ),
        migrations.RemoveField(
            model_name="sellerregistrationrequest",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="sellerregistrationrequest",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("seller", "Seller"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="SellerRegistrationRequest",
        ),
    ]
