# Generated by Django 5.2.4 on 2025-08-14 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveIndex(
            model_name="ad",
            name="store_ad_is_top_2c0a3b_idx",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="address",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="district",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="is_top",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="region",
        ),
        migrations.RemoveField(
            model_name="category",
            name="order",
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["published_at"], name="store_ad_publish_62f7fe_idx"
            ),
        ),
    ]
