# Generated by Django 5.2.4 on 2025-08-06 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_uz", models.CharField(max_length=100, null=True)),
                ("name_ru", models.CharField(max_length=100, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("phone", models.CharField(default="+998770367366", max_length=20)),
                (
                    "support_email",
                    models.EmailField(default="support@77.uz", max_length=254),
                ),
                (
                    "working_hours",
                    models.CharField(
                        default="Monday-Sunday 9:00-21:00", max_length=200
                    ),
                ),
                (
                    "working_hours_uz",
                    models.CharField(
                        default="Monday-Sunday 9:00-21:00", max_length=200, null=True
                    ),
                ),
                (
                    "working_hours_ru",
                    models.CharField(
                        default="Monday-Sunday 9:00-21:00", max_length=200, null=True
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("title_uz", models.CharField(max_length=200, null=True)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("content", models.TextField()),
                ("content_uz", models.TextField(null=True)),
                ("content_ru", models.TextField(null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_uz", models.CharField(max_length=100, null=True)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="common.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "region")},
            },
        ),
    ]
